#!/usr/bin/env bash
# $1 = command to run, commands:
# - start: start Redis container
# - status: get status of container, outputs "running" if Redis server is running,
#           "stopped" if the Redis container is stopped but still exists, and
#           "not found" if the Redis container does not exist.
container_cli="sudo podman"
container_name=dev-video-sync-redis
container_tag="redis:latest"

function die() {
    echo "redis: $@" >&2
    exit 1
}

case "$1" in
    start)
	   case $($0 status) in
		  running) die "already running" ;;
		  stopped) $container_cli start "$container_name" ;;
		  "not found") $container_cli run -d --net host --name "$container_name" "$container_tag" ;;
	   esac
	   ;;
    status)
	   if $container_cli ps | grep "$container_name" &> /dev/null; then
		  echo "running"
	   elif $container_cli ps -a | grep "$container_name" &> /dev/null; then
		  echo "stopped"
	   else
		  echo "not found"
	   fi
	   ;;
    stop)
	   case $($0 status) in
		  running)
			 $container_cli stop "$container_name"
			 $container_cli rm "$container_name"
			 ;;
		  stopped)
			 $container_cli rm "$container_name"
			 ;;
		  *) die "Cannot stop and remove redis if not running" ;;
	   esac
	   ;;
    logs)
	   case $($0 status) in
		  running)
			 $container_cli logs -f "$container_name"
			 ;;
		  *) die "Cannot get logs if Redis is not running" ;;
	   esac
	   ;;
    *)
	   die "first argument must be \"start\", \"status\", \"stop\", \"logs\""
	   ;;
esac
